controller:
  ingressClassResource:
    enabled: true
    default: true
  metrics:
    port: 10254
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"